[package]
name = "gloomy-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
gloomy-core = { path = "../gloomy-core" }
glam = { version = "0.25" }
anyhow = "1.0"
log = "0.4"
wgpu = { workspace = true }
pollster = { workspace = true }
image = "0.25.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3"
